// Module: App
export const APP_SET_IS_READY = 'APP_SET_IS_READY'
export const APP_SET_IS_LOADING = 'APP_SET_IS_LOADING'
export const APP_SET_SNACKBAR = 'APP_SET_SNACKBAR'
export const APP_SET_DRAWER = 'APP_SET_DRAWER'

// Module: Dashboard
export const DASHBOARD_SET_LIST = 'DASHBOARD_SET_LIST'
export const DASHBOARD_CONCAT_LIST = 'DASHBOARD_CONCAT_LIST'
