// Module: App
export const APP_SET_IS_READY = 'APP_SET_IS_READY'
export const APP_SET_IS_LOADING = 'APP_SET_IS_LOADING'
export const APP_SET_SNACKBAR = 'APP_SET_SNACKBAR'
export const APP_SET_DRAWER = 'APP_SET_DRAWER'
