export { default as DashboardIntegrationConfig } from './DashboardIntegrationConfig.vue'
export { default as DashboardIntegrationList } from './DashboardIntegrationList.vue'
export { default as DashboardLayout } from './DashboardLayout.vue'
export { default as DashboardSettings } from './DashboardSettings.vue'
export { default as DashboardWidgetConfig } from './DashboardWidgetConfig.vue'
