export { default as DashboardIntegrationConfig } from './DashboardIntegrationConfig.vue'
export { default as DashboardAddIntegration } from './DashboardAddIntegration.vue'
export { default as DashboardIntegrations } from './DashboardIntegrations.vue'
export { default as DashboardLayout } from './DashboardLayout.vue'
export { default as DashboardSettings } from './DashboardSettings.vue'
export { default as DashboardWidgetConfig } from './DashboardWidgetConfig.vue'
export { default as DashboardWidgets } from './DashboardWidgets.vue'
